adding translation for abbreviations
wamserma/tex-tdl pull request #33
Opened 2016-10-24 14:08 UTC by kubatyszko

2016-10-24 19:22 UTC, wamserma requested changes
Sorry for being picky, but please review.

2016-10-24 19:22 UTC, wamserma commented on strings/pl_PL.tex
> +\def\tdl@SaSu{So/Nie/}
"So/Nie/" vs. "So/Nie" Typo or intended?

2016-10-24 21:50 UTC, kubatyszko commented
Ah, no there shouldn't be / at the end

2016-10-25 17:46 UTC, wamserma approved these changes

2016-10-25 17:47 UTC, merged